# Data Exploration

In [1]:
df_1 = (lambda: _deepnote_execute_sql('SELECT * FROM read_csv_auto(\'/work/art-collection.csv\')', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('SELECT * FROM read_csv_auto(\'/work/art-collection.csv\')', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
df_1

Name of Painter Subject of Painting                   Style       Medium  \
0               Noah            Seascape  Abstract Expressionism   Watercolor   
1            Vincent            Abstract  Abstract Expressionism     Charcoal   
2                Ava          Still Life                  Modern   Watercolor   
3               Liam            Wildlife                  Cubism      Acrylic   
4             Olivia           Landscape  Abstract Expressionism     Charcoal   
...              ...                 ...                     ...          ...   
2495           Pablo            Wildlife                 Realism  Mixed Media   
2496        Leonardo             Fantasy                  Modern   Watercolor   
2497            Emma           Landscape                  Modern          Oil   
2498            Liam            Portrait           Impressionism  Mixed Media   
2499            Jija             Fantasy           Impressionism   Watercolor   

         Size Frame     Location  Price ($)  Delivery (days)       Shipment  \
0     20"x30"   Yes      Chicago        459                6  Free Shipping   
1     20"x30"    No        Miami        657                6  Free Shipping   
2     18"x24"    No        Miami        907                7       Standard   
3     18"x24"    No      Calgary        649                3       Standard   
4     30"x40"   Yes        Miami        539                5  Free Shipping   
...       ...   ...          ...        ...              ...            ...   
2495  30"x40"    No     New York        469                5  Free Shipping   
2496  18"x24"   Yes      Chicago        943               10        Express   
2497  18"x24"    No      Toronto        469                9        Express   
2498  30"x40"   Yes  Los Angeles        605                6        Express   
2499  18"x24"    No     Montreal        746               10  Free Shipping   

      Color Palette Copy or Original Print or Real Recommended Environment  \
0     Neutral Tones         Original         Print                 Bedroom   
1        Cool Tones         Original         Print             Living Room   
2        Cool Tones         Original          Real                Kid Room   
3     Oceanic Tones         Original          Real                  Office   
4      Earthy Tones             Copy         Print                  Office   
...             ...              ...           ...                     ...   
2495   Earthy Tones             Copy         Print                 Bedroom   
2496   Earthy Tones         Original         Print             Living Room   
2497     Cool Tones         Original         Print                 Bedroom   
2498  Oceanic Tones         Original         Print                 Gallery   
2499     Cool Tones             Copy         Print                 Gallery   

     Mood/Atmosphere Theme/Lighting Requirements Reproduction Type  \
0            Calming               Natural Light      Screen Print   
1           Relaxing               Natural Light               N/A   
2             Joyful               Natural Light               N/A   
3         Reflective                Bright Light        Lithograph   
4          Energetic                Bright Light        Lithograph   
...              ...                         ...               ...   
2495          Joyful                Bright Light            Giclée   
2496         Calming               Natural Light      Screen Print   
2497          Joyful               Natural Light      Screen Print   
2498          Joyful                   Dim Light            Giclée   
2499       Energetic               Natural Light      Screen Print   

          Target Audience  
0       Corporate Clients  
1       Corporate Clients  
2       Corporate Clients  
3     Young Professionals  
4       Corporate Clients  
...                   ...  
2495   Interior Designers  
2496  Young Professionals  
2497             Families  
2498   Interior Designers

In [3]:
df_4 = (lambda: _deepnote_execute_sql('CREATE TABLE art AS SELECT * FROM read_csv_auto(\'/work/art-collection.csv\');\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('CREATE TABLE art AS SELECT * FROM read_csv_auto(\'/work/art-collection.csv\');\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
df_4

Count
0   2500

In [5]:
df_7 = (lambda: _deepnote_execute_sql('ALTER TABLE art RENAME COLUMN "Subject of Painting" TO painting_subject;\nALTER TABLE art RENAME COLUMN "Name of Painter" TO painter_name;\nALTER TABLE art RENAME COLUMN "Price ($)" TO price;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('ALTER TABLE art RENAME COLUMN "Subject of Painting" TO painting_subject;\nALTER TABLE art RENAME COLUMN "Name of Painter" TO painter_name;\nALTER TABLE art RENAME COLUMN "Price ($)" TO price;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
df_7

Empty DataFrame
Columns: [Success]
Index: []

## Who is the most famous painter?

How do you define a famous painter? 

1. By looking at the most number of paintings created?

2. By looking at the price point of selling paintings?

In [29]:
df_2 = (lambda: _deepnote_execute_sql('SELECT painter_name, COUNT(painter_name) AS \'total_paintings\' FROM art\nGROUP BY painter_name\nORDER BY total_paintings DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('SELECT painter_name, COUNT(painter_name) AS \'total_paintings\' FROM art\nGROUP BY painter_name\nORDER BY total_paintings DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
df_2

painter_name  total_paintings
0        Olivia              251
1          Jija              240
2         Pablo              239
3          Noah              238
4       Vincent              227
5          Emma              225
6      Leonardo              224
7          Liam              223
8         Frida              212
9        Claude              211
10          Ava              210

It looks like Olivia has the highest number of paintings. Let's explore the price point by painters.

In [35]:
df_9 = (lambda: _deepnote_execute_sql('SELECT painter_name, \n    AVG(price) AS \'avg_price\',\n    COUNT(*) AS \'total_paintings_sold\'\nFROM art\nGROUP BY painter_name\nORDER BY avg_price DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('SELECT painter_name, \n    AVG(price) AS \'avg_price\',\n    COUNT(*) AS \'total_paintings_sold\'\nFROM art\nGROUP BY painter_name\nORDER BY avg_price DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
df_9

painter_name   avg_price  total_paintings_sold
0          Liam  614.260090                   223
1      Leonardo  592.901786                   224
2         Frida  587.273585                   212
3        Olivia  582.677291                   251
4           Ava  575.766667                   210
5       Vincent  573.162996                   227
6          Jija  570.358333                   240
7          Noah  568.243697                   238
8          Emma  566.217778                   225
9         Pablo  562.485356                   239
10       Claude  551.796209                   211

It looks like Liam only sells 223 paintings but on average charges $614 per painting as compared to Olivia who only charges $582 per painting.

So does this mean that Liam is more famous? Let's look at how many paintings does Liam sell at what price point?

In [39]:
df_8 = (lambda: _deepnote_execute_sql('SELECT price, COUNT(*) FROM art\nWHERE painter_name = \'Liam\'\nGROUP BY price\nORDER BY price DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('SELECT price, COUNT(*) FROM art\nWHERE painter_name = \'Liam\'\nGROUP BY price\nORDER BY price DESC;', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
df_8

price  count_star()
0     975             3
1     965             1
2     943             2
3     938             1
4     933             4
..    ...           ...
87    161             1
88    157             2
89    149             1
90    130             2
91    127             2

[92 rows x 2 columns]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=13a90a7f-fdab-44fe-855c-ae8c9cbeedee' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>